name: Run Jest Tests and Build

on:
 push:
    branches: [ "main" ]
 pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build frontend
        run: npm run build
        env:
          CI: true 

      - name: Build backend
        run: npm run build-backend
        continue-on-error: true # Permite continuar si el script no existe

      - name: Run specific tests with coverage
        run: npm test -- --coverage pruebas/gamificacion/RecompensaTab.test.js pruebas/gamificacion/PacientesTab.test.js pruebas/gamificacion/ServiciosTab.test.js
        env:
          CI: true # Configura Jest para entornos CI

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build/

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage/
